version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - cv-uploads:/app/uploads
    networks:
      - hrms-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8100:80"
    depends_on:
      - backend
    networks:
      - hrms-network

volumes:
  cv-uploads:

networks:
  hrms-network:
    driver: bridge 